package presenter;

public enum EVENTS {
    C_BUTTON_VISIBILIDAD,C_BUTTON_RELACION,C_CONTROL_Y_LIBERTAD_USUARIO,C_BUTTON_CONSISTENCIA,C_PREVENCION_ERRORES,
    C_RECONOCIMIENTO, C_FLEXIBILIDAD, C_ESTETICA, C_RECUPERAR_ERRORES, C_DOCUMENTACION;
}
